name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              os: windows-latest,
              cxx: "cl",
            }
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Run CMake (Windows)
        run: |
          mkdir build
          cd build
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
        shell: cmd
      - name: Build (Windows)
        run: |
          cd build
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          ninja package
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: build/linkollector-win-[0-9].[0-9].[0-9]-win64.exe
